### PR TITLE
Danos ndpi updated with libndpi 3.4 (stable)

### PR DESCRIPTION
**Pull request by subhajit-cdot**
1. The branch danos_ndpi-3.4 was created from danos/ndpi "master" branch. ( Because the latest changes are on master branch, not in upstream branch, once danos_ndpi-3.4 will be merged in upstream, all changes should reflect to the upstream branch. 

2. There is a latest feature in nDPI-3.4, which is autotest with pcap file. However, there are few pcap files that have have inconsistent behavior across architecture due  to broken sorting in the test code. 
Please update debian/rules file (under "override_dh_auto_test:") accordingly while compiling the code. Moreover we can also disable the autotest feature for uniformity.

### CODE REVIEW

**Comment by pjaitken** [comment]
Thanks for the pull request! I compared it against nDPI's "3.4-stable" branch, and found some inconsistencies:

1. Some of your files files aren't in nDPI 3.4:

    ndpiReader.1
    fuzz/Makefile
    fuzz/.deps
    fuzz/.deps/fuzz_process_packet-fuzz_process_packet.Po
    fuzz/.deps/fuzz_ndpi_reader_with_main-fuzz_ndpi_reader.Po
    fuzz/.deps/fuzz_ndpi_reader-fuzz_ndpi_reader.Po
    src/include/Makefile.am
    src/include/ndpi_api.h
    tests/dnp3.pcap
    tests/iec60780-5-104.pcap
    tests/pcap/dnscrypt.pcap
    tests/pcap/msnms.pcap
    tests/result/dnscrypt.pcap.out
    tests/result/msnms.pcap.out

2. Some of the nDPI 3.4 files are missing from your branch:

    src/include/ndpi_api.h.in
    tests/pcap/exe_download.pcap
    tests/pcap/ftp_failed.pcap
    tests/pcap/fuzz-2006-06-26-2594.pcap
    tests/pcap/gquic.pcap
    tests/pcap/quic-23.pcap
    tests/pcap/quic-24.pcap
    tests/pcap/quic-27.pcap
    tests/pcap/quic-28.pcap
    tests/pcap/quic-29.pcap
    tests/pcap/quic-mvfst-22.pcap
    tests/pcap/quic-mvfst-27.pcap
    tests/pcap/quic-mvfst-exp.pcap
    tests/pcap/quic_q50.pcap
    tests/pcap/quic_t50.pcap
    tests/pcap/quic_t51.pcap
    tests/unit/Makefile.in
    .appveyor.yml
    .lgtm/*

3. subhajit-cdot/.travis.yml and ndpi/.travis.yml differ

4. In debian/patches, it should not be necessary to create new patch files for 3.4 - just refresh and update the existing patches.
    git ensures that the old versions are still be available in the relevant branches.

**Comment by pjaitken** [comment]
xref to the related [dataplane PR](https://github.com/danos/vyatta-dataplane/pull/4).

**Comment by subhajit-cdot** [comment]
Thanks @pjaitken . 

1.  
    a.  I should have added these auto generated fuzz files in .gitignore.
    b.  src/include/Makefile.am came from danos ndpi repo [/https://github.com/danos/ndpi/tree/master/src/include/Makefile.am](url)
    c.  src/include/ndpi_api.h was also in the danos ndpi previous version.(3.0.2) [/https://github.com/danos/ndpi/tree/master/src/include/ndpi_api.h](url)
    d.  tests/dnp3.pcap , tests/iec60780-5-104.pcap, tests/pcap/dnscrypt.pcap are obsolete in latest ndpi-3.4, so these also can be removed.
    e.  pcap.out needs to removed from the repo.

2. PCAP files were removed while compiling because these pcap auto tests were failed in my system. I kept those rm in debian/rules, however I mistakenly removed those from git as well. I can see src/include/ndpi_api.h.in, tests/unit/Makefile.in
.appveyor.yml, .lgtm/* in my local repo, they somehow missed.

3. I will check .travis.yml

4. I have tried with quilt refresh, but it was needed to edit the patches somehow to make it work. That's why I generated separate patch files for 3.4. Anyway if you can suggest appropriate commands for patch refresh, I can try once.

Should I create a new PR for the above changes?

Regards,
Subhajit

**Comment by pjaitken** [comment]
Thanks Subhajit, please update this PR as you described. There's no need to open a new PR.
"quilt refresh" should update the existing patches without needing to create new ones.

**Comment by pjaitken** [comment]
debian/libndpi3.0.* should be deleted since these are replaced with libndpi3.4.*

Looking at debian/patches:

series
    - please update the existing patches rather than adding new files

add-minor-version-to-soname.patch / add-minor-version-to-soname-ndpi-3.4-stable.patch
vyatta-category-file.patch / vyatta-category-file-ndpi-3.4-stable.patch
vyatta-increase-ndpi-num-bits.patch / vyatta-increase-ndpi-num-bits-ndpi-3.4-stable.patch
ndpireader-dynamic-link.patch / ndpireader-dynamic-link-ndpi-3.4-stable.patch
    - the new files are just refreshes of the existing ones (ie, only the line numbers changed).
    - do you really want to add your name to these and take responsibility for them?

Please refresh these patches:
    - ndpireader-dynamic-link-ndpi-3.4-stable.patch succeeded at 4 (offset -1 lines).
    - additional-cppflags-ndpi-3.4-stable.patch succeeded at 53 (offset 1 line).

vyatta-app-names.patch / vyatta-app-names-ndpi-3.4-stable.patch
    - the new file is just a refresh of the existing one, except that the explanatory comment was lost. Please add it back again.
    - do you really want to add your name to this and take responsibility for it?

additional-cppflags.patch / additional-cppflags-ndpi-3.4-stable.patch
define-have-json-c.patch / define-have-json-c-ndpi-3.4-stable.patch
    - OK; necessary patch file updates

vyatta-generation-ndpi-3.4-changes.patch
    - this patch should be merged into vyatta-generation.patch

vyatta-generation.patch / vyatta-generation-modified.patch
    - the changes to Makefile.am have been lost?

fix-makefile-prefix / fix-makefile-prefix-ndpi-3.4-stable.patch
    - the changes to configure.seed are vyatta specific, so please put them back in vyatta-generation*

vyatta-generated.patch / vyatta-generated-ndpi-3.4-changes.patch
    - in each of the yang files, keep the existing revision statement and append a new revision statement.
    - don't add the "free" enums, because those are not applications that can be matched so we don't want them in the CLI.
    - some of the name substitutions have gone wrong: none of the names should contain any special characters other than underscore:
        - "mssql-tds" should be "mssql_tds"
        - "targus dataspeed" should be "targus_dataspeed"
        - "sina(weibo)" should just be "weibo"
        - "whois-das" should be "whois_das"
        - "iot-scada" should be "iot_scada"
        - new names must only be appended to the end of the list, to preserve the existing values (for netconf). This is more important than keeping alphabetical order.
    - the generation/* scripts should help to generate the new files.

Thanks.

**Comment by subhajit-cdot** [comment]
@pjaitken I have added all missing files and removed unnecessary files as suggested, but I am still stuck with quilt refresh on the existing patch files. Need to understand few things here

1. Lets take "fix-makefile-prefix" for example

What I did is 
a. quilt push fix-makefile-prefix
b. quilt add src/lib/Makefile.in because this file is going to change after applying the patch.
c. copy latest src/lib/Makefile from ndpi-3.4 because latest version has lots of change in src/lib/Makefile.
d. quilt refresh


The problem is quilt refresh is refreshing the fix-makefile-prefix but all the new changes from new Makefile.in are getting included in the patch file along with the expected offset refresh. Is it expected? Please suggest steps to generate/refresh an existing patch.
Thanks


Subhajit

**Comment by subhajit-cdot** [comment]
@pjaitken 
I have updated name substitutions with underscore and appended new app names, types at the end of the yangs .. keeping the old enums unchanged. Therefore, even if there are free enums for obsolete applications, we will show those apps in the CLI. That is fine and may be we can show warning during commit/validation that "this app is not supported in current ndpi version" otherwise that configuration will not have any effect in reality.

Subhajit

**Comment by pjaitken** [comment]
Thanks again, @subhajit-cdot .

1. There's no need to keep the old patch files since git does all the necessary version tracking. Please update all the patch files in place (ie, using the same file names); don't create new patch files. In the changelog remove "also kept old files" / "kept old files".

2. The original author and description has been lost from each modified patch file. Please reinstate that information. Some patch files might have no changes at all, or just the line numbers change.

3. Two patch files succeeded, but with the wrong offset. These patches need to be refreshed:

    ndpireader-dynamic-link-ndpi-3.4-stable.patch
    * Hunk #1 succeeded at 4 (offset -1 lines).

    additional-cppflags-ndpi-3.4-stable.patch
    * Hunk #1 succeeded at 53 (offset 1 line).

4. fix-makefile-prefix-ndpi-3.4-stable.patch is not a "vyatta" patch. For modularity, we want to retain the debian patches consistent with the debian nDPI fork, and only add vyatta specific things in vyatta patches. So please don't add "generation" to configure.seed in this patch.

5. vyatta-generation-modified.patch is missing changes to Makefile.am and configure.seed. Please add the missing Makefile.am changes, and move the configure.seed changes from fix-makefile-prefix*.patch into this patch.

Thanks,
P.

**Comment by pjaitken** [comment]
@subhajit-cdot , in vyatta-ndpi-application-names-v1.yang and vyatta-ndpi-application-types-v1.yang, please put the new revision statement first, ahead of the existing revision statement.

If you're able to check these with yangc, you would see:

`module vyatta-ndpi-application-names-v1: revision block out of order 2020-11-02`
`module vyatta-ndpi-application-types-v1: revision block out of order 2020-11-02`

Additionally, in each case please ensure that the "revision 2020-11-02" is prefixed with a single tab rather than eight spaces.

Thanks.

**Comment by subhajit-cdot** [comment]
Thanks @pjaitken . I am updating both yang and patch files.

**Comment by subhajit-cdot** [comment]
Thanks @pjaitken .

I have updated files as per your suggestions, also checked yang files using yangc. My custom branch is 2 commits ahead, do I need to generate PR again or latest changes will be fetched automatically in the existing PR?

Here are my doubts regarding the latest changes..

1. **"New enums MUST only be added to the end of this list.
     Old enums MAY be deprecated or obsoleted, but must not be removed."** 
I have followed this, however, can you please brief me how deprecated or obsoleted app names will be supported in CLI? for eg. office365 and microsoft365 both are there in the current yang file, how will these conflicts  be resolved in CLI?

2. Newly refreshed patch files have old author names only (no new name inserted).  However, after refreshing the patches using quilt, most of the patch files become "-p1 style" patch,  I have used quilt args "-p ab", hope this will not violate any patch standard. Few patch files don't have author name, eg. vyatta-increase-ndpi-num-bits.patch, I have not included anything there. 

3. As I mentioned previously, override_dh_auto_test of debian/rules removes pcap files which are not compatible in my build environment. However, it can be edited accordingly.
[# disable tests that have inconsistent behavior across architecture due to broken sorting in the test code]

4.   "Please add the missing Makefile.am changes, and move the configure.seed changes from fix-makefile-prefix*.patch into this patch." --- 
The Makefile.am already has the desired changes.(@EXTRA_TARGETS@) Therefore we don't need to add this in the patch file. Therefore I have removed old changes for Makefile.am from vyatta-generation.patch.

Thanks

Subhajit

**Comment by subhajit-cdot** [comment]
Hi @pjaitken 
Have you checked the patches? Is there anything missing from my side? Please let me know. 

Thanks

-Subhajit

**Comment by pjaitken** [comment]
@subhajit-cdot, this looks good! Sorry for not getting back to you sooner.

Answering your questions:

0. My custom branch is 2 commits ahead, do I need to generate PR again or latest changes will be fetched automatically in the existing PR?

--> I can see your three commits, so it's fine.

1. can you please brief me how deprecated or obsoleted app names will be supported in CLI? for eg. office365 and microsoft365 both are there in the current yang file, how will these conflicts be resolved in CLI?

--> These should be marked as "status obsolete" to prevent them from being shown in the CLI:
```
    enum "office365" {
        status obsolete;
    }
```

2. Newly refreshed patch files have old author names only (no new name inserted). However, after refreshing the patches using quilt, most of the patch files become "-p1 style" patch, I have used quilt args "-p ab", hope this will not violate any patch standard. Few patch files don't have author name, eg. vyatta-increase-ndpi-num-bits.patch, I have not included anything there.

--> The aim was to make minimal changes while refreshing the patches, so this looks good. 

3. As I mentioned previously, override_dh_auto_test of debian/rules removes pcap files which are not compatible in my build environment. However, it can be edited accordingly.

--> Your diff compares exactly with the ndpi 3.4 branch, so I don't see the issue.

4. The Makefile.am already has the desired changes.(@EXTRA_TARGETS@) Therefore we don't need to add this in the patch file. Therefore I have removed old changes for Makefile.am from vyatta-generation.patch.

--> I noticed that in vyatta-generation.patch that "generation" is nolonger being added to SUBDIRS in Makefile.am, but is being added to EXTRA_TARGETS in configure.seed.


So the only thing to do is to add "status obsolete;" for the removed application names. When you're doing that, could you also remove the trailing whitespaces in debian/changelog?

Thanks!

**Comment by subhajit-cdot** [comment]
@pjaitken Please check the last commit. Thanks

**Comment by pjaitken** [comment]
@subhajit-cdot we've been thinking about the best way to merge this code.

1. You've opened the PR against the "upstream" branch. However, it contains vyatta specific patches which shouldn't be in "upstream".
2. Since your branch was created from the "master" branch, it easily merges back into master. However this could create some difficulty when a new upstream version arrives.

One solution would be to convert the whole diff into a (huge!) patch which can be applied directly to the master branch, and can be easily removed once 3.4 (or later) is available upstream.

Another solution would be to update the debian nDPI repo to 3.4, and pull that into the upstream branch as a regular upstream update. I've reached out to the debian nDPI maintainer to check whether there are any plans to update it.

**Comment by subhajit-cdot** [comment]
@pjaitken 
As I mentioned earlier, I took from master branch because the latest changes are on master branch and upstream branch is quiet older (even danos/2009 changes are not updated in upstream branch). However I was asked to send PR into the upstream branch. 
As it can be easily merged with both master and upstream branch , can we separate out vyatta-specific changes with another commit on the the upstream after taking this pull request?

However, as you said, if nDPI upgrades to debian 3.4 then we can pull that to upstream, else the huge patch file apply to master branch would be a practical temporary solution.

Thanks.

Subhajit

**Comment by scott-leishman** [comment]
Thanks, Subhajit. DANOS ndpi has now been updated to version 3.4.

**Pull request closed without merging**
